# Generated by Django 3.1.5 on 2021-02-01 01:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_picture_URL', models.URLField(blank=True, null=True)),
                ('number_of_credits', models.IntegerField(default=0)),
                ('RUC', models.CharField(blank=True, max_length=11, null=True)),
                ('DNI', models.CharField(blank=True, max_length=8, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_advertiser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('ag', 'Agricultor'), ('an', 'Anunciante'), ('co', 'Comprador')], max_length=2, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='agricultores.department')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilogramos'), ('ton', 'Toneladas')], max_length=3)),
                ('unit_price', models.FloatField()),
                ('area_unit', models.CharField(choices=[('hm2', 'Hectáreas'), ('m2', 'Metros cuadrados')], max_length=3)),
                ('area', models.FloatField()),
                ('harvest_date', models.DateTimeField()),
                ('sowing_date', models.DateTimeField()),
                ('picture_URLs', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, size=None)),
                ('supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultores.supply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilogramos'), ('ton', 'Toneladas')], max_length=3)),
                ('unit_price', models.FloatField()),
                ('area_unit', models.CharField(choices=[('hm2', 'Hectáreas'), ('m2', 'Metros cuadrados')], max_length=3)),
                ('area', models.FloatField()),
                ('desired_harvest_date', models.DateTimeField()),
                ('desired_sowing_date', models.DateTimeField()),
                ('supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultores.supply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='agricultores.department')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='agricultores.region')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reach', models.IntegerField()),
                ('harvest_date', models.DateTimeField()),
                ('sowing_date', models.DateTimeField()),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultores.supply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddressedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultores.advertisement')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultores.district')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='agricultores.district'),
        ),
    ]
