# Generated by Django 3.1.5 on 2021-02-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
