# Generated by Django 3.1.5 on 2021-01-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
