# Generated by Django 3.1.5 on 2021-01-11 22:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DNI',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='RUC',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_advertiser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_URL',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
