# Generated by Django 3.1.5 on 2021-03-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0002_auto_20210224_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publish',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
