# Generated by Django 3.1.5 on 2021-01-12 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0002_auto_20210112_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='agricultores.department'),
        ),
    ]
