# Generated by Django 3.1.5 on 2021-01-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0002_auto_20210111_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DNI',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='RUC',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
