# Generated by Django 3.1.5 on 2021-01-11 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0003_auto_20210111_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_URL', models.URLField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('Kg', 'Kilogramos'), ('g', 'Gramos')], max_length=2)),
                ('quantity', models.IntegerField()),
                ('harvest_date', models.DateTimeField()),
                ('sowing_date', models.DateTimeField()),
                ('unit_price', models.FloatField()),
                ('supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultores.supplies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('Kg', 'Kilogramos'), ('g', 'Gramos')], max_length=2)),
                ('number', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('desire_harvest_date', models.DateTimeField()),
                ('desire_sowing_date', models.DateTimeField()),
                ('supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultores.supplies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
