# Generated by Django 3.1.5 on 2021-03-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0003_auto_20210303_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name': 'Cultivo', 'verbose_name_plural': 'Cultivos'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['name'], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='supply',
            name='cultivos_sin_vender',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='cultivos_vendidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='pedidos_completados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='pedidos_por_completar',
            field=models.IntegerField(default=0),
        ),
    ]
