# Generated by Django 3.1.5 on 2021-01-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0003_auto_20210112_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='agricultores.department'),
        ),
    ]
