# Generated by Django 3.1.5 on 2021-01-12 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0004_auto_20210112_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='agricultores.department'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='agricultores.region'),
        ),
    ]
