# Generated by Django 3.1.5 on 2021-01-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0004_auto_20210125_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='supplies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultores.supply'),
        ),
    ]
