# Generated by Django 3.1.5 on 2021-03-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0004_auto_20210303_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='cultivos_sin_vender',
            new_name='total_sold',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='cultivos_vendidos',
            new_name='total_solved',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='pedidos_completados',
            new_name='total_unsold',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='pedidos_por_completar',
            new_name='total_unsolved',
        ),
    ]
