# Generated by Django 3.1.5 on 2021-03-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0005_auto_20210303_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='total_sold',
            new_name='sold_publications',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='total_solved',
            new_name='solved_orders',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='total_unsold',
            new_name='unsold_publications',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='total_unsolved',
            new_name='unsolved_orders',
        ),
    ]
