# Generated by Django 3.1.5 on 2021-01-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0007_auto_20210113_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultores.district'),
        ),
    ]
