# Generated by Django 3.1.5 on 2021-01-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0008_auto_20210113_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultores.department'),
        ),
    ]
