# Generated by Django 3.1.5 on 2021-04-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0008_auto_20210407_0644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressedTo',
            new_name='LinkedTo',
        ),
    ]
