# Generated by Django 3.1.5 on 2021-04-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0009_auto_20210407_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='picture_URLs',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='picture_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
