# Generated by Django 3.1.5 on 2021-04-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0010_auto_20210413_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
