# Generated by Django 3.1.5 on 2021-04-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0011_advertisement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_of_credits',
        ),
    ]
