# Generated by Django 3.1.5 on 2021-04-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0012_remove_user_number_of_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_credits',
            field=models.IntegerField(default=0),
        ),
    ]
