# Generated by Django 3.1.5 on 2021-04-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0013_user_number_of_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='original_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
