# Generated by Django 3.1.5 on 2021-04-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0014_advertisement_original_credits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['user'], 'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AlterModelOptions(
            name='linkedto',
            options={'verbose_name': 'Anuncio - Insumo', 'verbose_name_plural': 'Anuncios - Insumos'},
        ),
        migrations.RemoveField(
            model_name='supply',
            name='sold_publications',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='solved_orders',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='unsold_publications',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='unsolved_orders',
        ),
    ]
