# Generated by Django 3.1.5 on 2021-05-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agricultores', '0016_user_date_of_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_creation',
            new_name='registration_day',
        ),
    ]
